### ISSUE TITLE
Hello from the Kopano team

### ISSUE THREAD

**Issue by fbartels** [mlan/docker-kopano#1]
Hi @mlan,

just browsed through your Repo looks quite nice. 

> Hopefully this repository can be retired once the Kopano community make official images available. There is some evidence of such activity on dockerhub:kopano.

The images that you can find in there are based on https://github.com/zokradonh/kopano-docker. It started as a commuity project and I have already invested quite some effort to make this easier to use and extend it with more functionality. Depending on user feedback it is also scheduled to get its "official" status.

What do you think of joining forces?

**Comment by mlan** [comment]
Hello @fbartels 

Many thanks for the kind words and that you are considering me joining forces with the Kopano team. :) May I suggest that we try to arrange a call this coming week to figure out how our interests overlap? 

You can contact me directly here mlan at circuit - factory dot com.

**Comment by fbartels** [comment]
Hi @mlan ,

I've spent some time yesterday to get your compose file running, but since not all included images are public I did not run out of the box (in your openldap container there is no public 1.0 and I was unable to find your mail container). Are the script https://github.com/mlan/docker-kopano/blob/master/assets/conf and https://github.com/mlan/docker-kopano/blob/master/assets/setup-runit.sh your own or did you adopt them from somewhere else? For the conf script I am wondering about this, since it seems to be that you duplicating its capabilities in the entrypoint script (e.g. https://github.com/mlan/docker-kopano/blob/master/assets/entrypoint.sh#L49-L62).

The goal for the linked project is already in the description of it:

> This repository contains an easy to replicate recipe to spin up a Kopano demo environment, which can (through modification of .env and possibly docker-compose.yml) also be used for production environments.

For this the project already bundles an ldap that comes with some demo users, but I am not married to this fact and am open to pull requests that make the demo users optional (e.g. additional questions in setup.sh that then choose the appropriate ldap container). 

For delivery everyone should be able to use this with the community packages or rebuild the images based on our subscription packages. Customers will later also be able to pull pre-built images based on the subscription packages from a private registry.

**Comment by mlan** [comment]
Hello @fbartels 

I am about to release the mlan/postfix-amavis and a the new version of mlan/openldap (hopefully) later this week. I will give you a ping when I do.

The scripts are my design. I have been working on this repository for some time and there has been several periods of refactoring, and some redundancy have remained, it seems. :) I should clean it up.

And, yes, I think your goal sounds good.

How do you think we kick off our collaboration effort?

**Comment by fbartels** [comment]
hm.. good question. For one I really still like some more feedback on the general image. Seeing that you also added a Makefile a review of the the Makefile in the other repo would be welcome.

Functionality wise I still the need to have config.php of webapp and z-push (and the config files of the individual webapp plugns) configurable through env variables.

**Comment by mlan** [comment]
At the moment, I have my hands full preparing the mlan/postfix-amavis repo and a the new version of mlan/openldap. But, sure, once that is done with, I will spend some time with the general image and come with feedback.

**Comment by fbartels** [comment]
Thanks

**Comment by mlan** [comment]
Hello @fbartels

I have now released the supporting repos and updated the compose file, so the demo should now run "out of the bow". :)
