### ISSUE TITLE
add a simple way  via .env  for ldap/AD config

### ISSUE THREAD

**Issue by osnet** [mlan/docker-kopano#10]
In my hours of forced homeoffice : ) i made the kopano docker  connect with a SAMBA4 AD // AD 
To enable this feature you have to add / overwrite some configfiles.

- Enable LDAP bind to handle selfsigned SSL Certs in the connection to ldaps server
```
    volumes:
       [...]
      - ./config/ldap-cert.cfg:/etc/ldap/ldap.conf # allow insecure/selfsigned tls 
```
``ldap-cert.cfg`` contains

```
#
# LDAP Defaults
#

# See ldap.conf(5) for details
# This file should be world readable but not world writable.

#BASE	dc=example,dc=com
#URI	ldap://ldap.example.com ldap://ldap-master.example.com:666

#SIZELIMIT	12
#TIMELIMIT	15
#DEREF		never

# TLS certificates (needed for GnuTLS)
############################
TLS_REQCERT allow            ####
############################
TLS_CACERT	/etc/ssl/certs/ca-certificates.crt
```

- Enable Kopano-Docker to speak with the ldap directory and receive needed data

```
    volumes:
      [...]
      - ./config/ldap.cfg:/etc/kopano/ldap.cfg   # ldap attributes etc

```

``config/ldap.cfg``  contains something like this:

```
#######
## This part is partly generated from existing variables in .env
#######
ldap_starttls = no
ldap_uri = ldaps://111.222.333.444:636/
ldap_search_base = dc=example,dc=com
ldap_user_type_attribute_value = user
ldap_group_type_attribute_value = group
ldap_bind_user = cn=ldapbind,cn=Users,dc=example,dc=com
ldap_bind_passwd = TopSecret

#########
# Object settings : These variables did not work placing them in .env
#########
ldap_object_type_attribute = objectClass
ldap_user_type_attribute_value = User
ldap_group_type_attribute_value = Group
ldap_contact_type_attribute_value = Contact
ldap_company_type_attribute_value = ou
ldap_addresslist_type_attribute_value = kopano-addresslist
ldap_dynamicgroup_type_attribute_value = kopano-dynamicgroup
ldap_user_search_filter = (kopanoAccount=1)
ldap_user_unique_attribute = objectGUID
ldap_user_unique_attribute_type = binary
ldap_fullname_attribute = displayName
ldap_loginname_attribute = sAMAccountName
ldap_emailaddress_attribute = mail
ldap_emailaliases_attribute = otherMailbox

######
#  Other ticket : ) [#5](https://github.com/mlan/docker-kopano/issues/5)
######
!propmap /etc/kopano/ldap.propmap.cfg

```

Thanks for having patience with the wishes of an grumpy old sysadmin : DD

**Comment by mlan** [comment]
@osnet Many thanks for sharing this. I think this information can be very valuable for someone trying to set up something similar to what you are doing.
So I'll take it that this is a request to include the variables under "Object settings : These variables did not work placing them in .env".

**Comment by mlan** [comment]
@osnet 

In f13d2d2329d7b08a388ca5368e2a9305936b51d3 the variable lookup function was changed. Now, Kopano man pages and sample config files are used to find valid keys to match environment variables. So now all valid keys should work.

Please come back here if the issue remains. Mark as closed.

**Comment by mlan** [comment]
Hi @osnet

The accessibility of this information would certainly benefit from it being consolidated on the [wiki page](https://github.com/mlan/docker-kopano/wiki).
