### ISSUE TITLE
webaccess broken

### ISSUE THREAD

**Issue by osnet** [mlan/docker-kopano#11]
Hi, 
i know i have a different volume setup than you ..  but i have encountered a lil bug : )

i thought with spinning up the new docker image revision it will overwrite its old configfiles. 

ERRRRR,  not as expected

in `` app-conf/webapp/config.php `` we have a value Line 45
``` define("INSECURE_COOKIES", true);```

After spinning up the stuff i got  Error400 in my borwsers.
Docker exec-it ....    curl 127.0.0.1:80   same thing.

Playing round with apache2 errorlogging within the container i got 
``` 
[Sat Nov 14 22:05:44.456956 2020] [php7:notice] [pid 1989] [client 192.168.222.20:49480] Rejected insecure request as configuration for 'SECURE_COOKIES' is true.

```

According to [kopano.io](https://documentation.kopano.io/webapp_admin_manual/config.html#secure-cookies)
we have to change our config.php 

just switch from 

``` define("INSECURE_COOKIES", true); ``` to ```define("SECURE_COOKIES", false);```

restart the containers 

all fine again... 

can you confirm this in some way ? or is this just me : PP

**Comment by osnet** [comment]
ah lol  wait ...  i had mounted my configs manually so they werent generated as they are now ... 
i guess i have to apply the docker.unlock thingy
i'll have a try tomorrow

**Comment by osnet** [comment]
i was right

**Comment by osnet** [comment]
apologize ..  with docker unlock stuf all ne settings got applied, yes
but the configfile    app-conf/webapp/config.php   did not get changed

**Comment by mlan** [comment]
@osnet 

Yes, the switch from `define("INSECURE_COOKIES", true);` to `define("SECURE_COOKIES", false);` was introduced in WebApp 5.0.0, see [Kopano WebApp HTTP access](https://github.com/mlan/docker-kopano#kopano-webapp-http-access).

To help with migrating older configurations I introduced in 230e6953fd436b529b454fb292df7320858a58e2 `MIGRATE_CONFIG=all`, see [MIGRATE_CONFIG=1 Rejected insecure request as configuration for SECURE_COOKIES is true](https://github.com/mlan/docker-kopano#migrate_config1-rejected-insecure-request-as-configuration-for-secure_cookies-is-true).

Mark as closed.
