### ISSUE TITLE
archiver possibility

### ISSUE THREAD

**Issue by osnet** [mlan/docker-kopano#12]
Hi, 
how much effort would it take to expand the functionality  with the kopano-archiver ? 
Til now i have read, that the archiver is a fully deployed kopano server with a little addon and config

[Kopano Archiver DOCS](https://documentation.kopano.io/kopano_archiver_manual/installation.html)

it would be nice to have the possibility with un/tagging some .env  points to spin up another mailserver just 4 archiving. 
mmh

**Comment by mlan** [comment]
Hi @osnet 

many thanks for raising this issue. I had a quick look and it does not appear too difficult to include the archiver.

**Comment by osnet** [comment]
ja man,  lockdown is coming, time to test some new stuff : ))

**Comment by mlan** [comment]
There appears to be an [issue](https://forum.kopano.io/topic/3560/kopano-archiver-depends-libkcarchiver0-10-0-3-but-10-0-6-installed?_=1607954910742) with the kopano-archiver package. Will wait for it to be resolved.

**Comment by mlan** [comment]
Hi @osnet 

The [issue](https://forum.kopano.io/topic/3560/kopano-archiver-depends-libkcarchiver0-10-0-3-but-10-0-6-installed?_=1607954910742) with the kopano-archiver package was resolved.

In 39fe4e82a15caeb5a1acfe4b49832fbda0bea61f support for the Kopano Archiver and the WebApp plugins S/MIME and MDM was provided. Please see the section [kopano archiver](https://github.com/mlan/docker-kopano#kopano-archiver) for a brief overview of the configuration procedure.
