### ISSUE TITLE
Migrating external postboxes to kopano

### ISSUE THREAD

**Issue by osnet** [mlan/docker-kopano#15]
Again i am bothering my friend @mlan with some useful tips : )

I am currently migrating ( testing stuff ) from mailcow to kopano. 
This can be done from inside the running docker container (app) with this 

```
kopano-migration-imap --noauthmd5  --host1 old-imap.example.com --user1 userold --password1 passw1  -sep2 / --prefix2 "" --host2 kopano.example.com --user2 usernew --password2 passw2
```
source: [Kopno.io](https://documentation.kopano.io/kopano_migration_manual/imap_migration.html)

my mailer deamons are secured with ssl/tls. there are no unencrypted ports open. so i there was a problem synching.
the kopano-gateway is dull and is not able to handle encrypted conenctions. 

in order to user  ``--ssl`` or ``--tls``    instead of ``--noauthmd5`` you have to temporarily enhance kopano with the following steps.

1. Install  SSLeay :  `` apt update && apt-get install libnet-ssleay-perl libcrypt-ssleay-perl -y ``
2. Install cpan net io SSL  : `` cpan install IO::Socket::SSL ``

After that  you are able to migrate from an old imap mailbox to a sepific ( already aktive ) user

Just like 

```
root@96f2dcc77ba7:/# kopano-migration-imap --tls1  --host1 mailcow --user1 user@mailcow.muh --password1 oinkoink  -sep2 / --prefix2 "" --host2 localhost --user2 kopanouser --password2 password
```

The sync ist starting. if not runnig tmux or someting.  leave that terminal opened, otherwise  sync will get broken

**Comment by osnet** [comment]
NOTE: 
please read the manual for  imapsync,  there may occur  problems  if   theusernames on both hosts are slightly different

**Comment by mlan** [comment]
Hi @osnet 

Many thanks for sharing this tutorial with us!

**Comment by mlan** [comment]
Hi @osnet 

It would be a shame to hide away this very useful information in a closed issue. I have created a skeleton [wiki page here](https://github.com/mlan/docker-kopano/wiki). Perhaps you can help me consolidating the information there?
