### ISSUE TITLE
enhancement: export tool from kopano contacts

### ISSUE THREAD

**Issue by osnet** [mlan/docker-kopano#22]
hi @mlan, 

i am now serving ~ 50 postboxes with 85% of your kopano version : )
to sync our cloud pbx phonebook with the publicfolder contacts  i want to use a small script from kopano it self

[contact2csv](https://stash.kopano.io/projects/KSC/repos/core-tools/browse/contacts2csv)

but i do not have any chance to get this running. 
maybe i am blind, could be, : ) but to get this running i'd need to install some extra dependencies

- kopnolibs
- python-kopano
- python-mapi

maybe i have to stop apt from updating z-push, cause this got broken applying the update : )

maybe you can add this niceone directly to you stuff ?

thanks mate

**Comment by fbartels** [comment]
I would rather recommended to use https://stash.kopano.io/projects/SPS/repos/kopano-contacts-exporter/browse instead.

Or look at the Kopano RestAPI (compatible with Microsoft Graph).

**Comment by osnet** [comment]
@fbartels  did anyone tried to build this for pub contacts ?

**Comment by fbartels** [comment]
For the RestAPI that is already possible. For the script i posted this has not been done (by us) since it was not in the scope of the customer project. But if you adapt the script a pull request is always welcome.

**Comment by mlan** [comment]
I believe the question has been answered.
