### ISSUE TITLE
spamlearn inotify

### ISSUE THREAD

**Issue by osnet** [mlan/docker-kopano#23]
hellaz,
me again : ) 
any chance to build in this nice stuff  ?
[inotify spam learn](https://github.com/bkram/inotify-spamlearn)

**Comment by mlan** [comment]
Hi @osnet 

There already is support for kopano-spamd, see [Kopano-spamd integration with mlan/postfix-amavis](https://github.com/mlan/docker-kopano#kopano-spamd-integration-with-mlanpostfix-amavis).

If I'm not mistaken, for [inotify-spamlearn](https://github.com/bkram/inotify-spamlearn) to work in a docker-based setup it needs to run in the container that also have spamassassin running. So perhaps it is the MTA container that needs to provide this support?
  
One such implementation of kopano-spamd support in a MTA container is described here [Kopano-spamd integration with mlan/kopano](https://github.com/mlan/docker-postfix-amavis#kopano-spamd-integration-with-mlankopano).
