### ISSUE TITLE
add ldap propmap

### ISSUE THREAD

**Issue by osnet** [mlan/docker-kopano#5]
Hi, 
since i am using  EAS or webapp i did not test imap ... 
LDAP works fine for EAS and web  out of the box.
BUT
if you need to enable imap ( ya i needed to .. gitlab-ce :P ) then you have to add some extra files  for  getting stuff to work.

1. add  [ldap.propmap.cfg](https://github.com/Kopano-dev/kopano-core/blob/master/installer/linux/ldap.propmap.cfg) to  ``app.conf/``
2. add `` !propmap /etc/kopano/ldap.propmap.cfg `` to the bottom of ``app-conf/ldap.cfg``

after make all ( compose  stop rm start ) the ldap/ad extension properties are synched (per user) and overwriting default disabled features like imap pop and so on... 

thanks for reading : ))

**Comment by mlan** [comment]
Hello @osnet 

Very good. I will consider including this in the documentation and demo.

Many thanks for sharing this.

**Comment by mlan** [comment]
@osnet 

In 611d4ae6949d3e07cb1bdf7e6bcb37d4f976d7d3 I introduced the variable `LDAP_PROPMAP=` that should address this request, see [Kopano LDAP attributes LDAP_PROPMAP](https://github.com/mlan/docker-kopano#kopano-ldap-attributes-ldap_propmap).

Mark as closed.
