### ISSUE TITLE
add kdav

### ISSUE THREAD

**Issue by osnet** [mlan/docker-kopano#6]
[Kopano Groupware Bitbucket](https://stash.kopano.io/projects/KC/repos/kdav/browse?at=f6e967dd271)
[Github Kopano-dev](https://github.com/Kopano-dev/kdav)

would be a nice feature to be build in

**Comment by mlan** [comment]
Hi @osnet 

Many thanks for sharing this. How do you envision using kdav in relation to z-push? Both supported by a single server? Or a server supporting either one but not both?

For others coming here I just want to point out that [z-push](https://z-push.org/), already integrated, provides these features and more for ActiveSync capable devices.

**Comment by osnet** [comment]
Just to mention, my poeple and me are using  95%  linux desktops
If ever evaluated as a good replacement for the currently mailserver  there will be the need  having 
mail in, mail out,  calendars and  contacts  on  thunderbird, evolution  and co. 
On handhelds, tablets and co   EAS  is ok.

**Comment by osnet** [comment]
closed.  solved with nginx proxy

**Comment by mlan** [comment]
@osnet 

I understand that there is a way to address this issue using a proxy. If you have the time I love to learn more about how this works.

**Comment by stefangries** [comment]
Is there a way to sync Kopano contacts with Apple Contacts (OSX, not iOS) besides kDAV?

**Comment by osnet** [comment]
eas

**Comment by stefangries** [comment]
AFAIK Apple Mail/Calendar/Contacts only supports Exchange Web Services (EWS), but not ActiveSync (EAS).

**Comment by osnet** [comment]
nimmst halt das 
https://www.messageconcept.com/de/news/how-to-sync-exchange-contact-folders-to-your-mac-os-x-addressbook/
